var otherUniversities = [
{"web_page": "http://www.brussels.uibs.org/", "country": "Belgium", "domain": "brussels.uibs.org", "name": "UIBS: Brussels Business School"},
{"web_page": "http://www.umss.edu.bo/", "country": "Bolivia", "domain": "umss.edu.bo", "name": "Universidad Mayor de San Simon"},
{"web_page": "http://www.unisc.br/portal/pt", "country": "Brazil", "domain": "unisc.br", "name": "Universidade de Santa Cruz do Sul"},
{"web_page": "http://portal.estacio.br/", "country": "Brazil", "domain": "estacio.br", "name": "Universidade Estácio de Sá"},
{"web_page": "http://www.uva.br/", "country": "Brazil", "domain": "uva.br", "name": "Universidade Veiga de Almeida"},
{"web_page": "http://www.u-paris2.fr/52966480/1/fiche___pagelibre/&RH=ACCUEIL_FR&RF=ACCUEIL_EN", "country": "France", "domain": "u-paris2.fr", "name": "Université Paris 2 Panthéon-Assas"},
{"web_page": "http://www.tu-berlin.de/", "country": "Germany", "domain": "tu-berlin.edu", "name": "Technische Universität Berlin"},
{"web_page": "https://www.unah.edu.hn/", "country": "Honduras", "domain": "unah.edu.hn/", "name": "Universidad Nacional Autónoma de Honduras"},
{"web_page": "http://www.mnit.ac.in/", "country": "India", "domain": "mnit.ac.in/", "name": "Malaviya National Institute of Technology, Jaipur"},
{"web_page": "https://www.unibocconi.eu/wps/wcm/connect/Bocconi/SitoPubblico_EN/Navigation+Tree/Home/", "country": "Italy", "domain": "unibocconi.eu.com", "name": "Bocconi University"},
{"web_page": "http://www.itesm.mx/wps/wcm/connect/ITESM/Tecnologico+de+Monterrey/English", "country": "Mexico", "domain": "itesm.mx", "name": "Tecnológico de Monterrey"},
{"web_page": "http://www.universityofthevisayas.com/", "country": "Philippines", "domain": "universityofthevisayas.com", "name": "University of the Visayas"},
{"web_page": "http://www.uct.ac.za/", "country": "South Africa", "domain": "uct.ac.za/", "name": "University of Capetown"},
{"web_page": "http://rsu.edu.sd/en/", "country": "Sudan", "domain": "rsu.edu.sd/en/", "name": "Red Sea University"},
{"web_page": "http://www.lacademie.com/", "country": "USA", "domain": "lacademie.com", "name": "l'Academie de Cuisine"},
{"web_page": "http://www.lonestar.edu/montgomery.htm", "country": "USA", "domain": "lonestar.edu", "name": "Lone Star College: Montgomery"},
{"web_page": "http://www.lonestar.edu/northharris.htm", "country": "USA", "domain": "lonestar.edu", "name": "Lone Star College: North Harris"},
];